### ISSUE TITLE
Support role ids for Modmail roles/auth

### ISSUE THREAD

**Issue by svemat01** [khakers/modmail-viewer#35]
Add support for checking if a user is part of any Discord role ids that are set as Modmail Roles (Supporter, Adminstrator etc...)

**Comment by khakers** [comment]
Will start implementing this after I've got the current frontend changes in a mostly stable state to build off of. Hopefully will be able to make it into the next release.

For my future reference:

It looks like adding the 
`guilds.members.read` scope will allows us to use the `/users/@me/guilds/{guild.id}` [endpoint](https://discord.com/developers/docs/resources/user#get-current-user-guild-member) to retrieve the roles the user has and match them against the allowed roles.

**Comment by khakers** [comment]
Just pushed an initial implementation of this to the develop branch (if you decide to test this, be aware that develop currently has a substantial number of changes awaiting v0.6.0). There are some quirks to document about the implementation of this feature that users should be aware of:

* The user's *Discord Roles* are stored within their auth token.

  * This means that if a users roles change after they authenticate, this change is not reflected until the user is issues a new authentication token, which happens upon sign in through discord. For instance, if you assign a user a new role (such as a supporter being given a moderator role), this won't be reflected unless they sign out and back in. If you revoke a users access by removing their role, it will take up to 3 hours for that user to lose access to the website (when their token expires).
   * Tokens are not easily revocable (you may globally revoke tokens by changing your secret key (`MODMAIL_VIEWER_DISCORD_GUILD_ID`))
  
* The user's highest _modmail role_ should always be used based on both discord roles and manually assigned roles.

* Discord role permissions are synced with your MongoDB database
  *  Changing the _modmail role_ of a *Discord role* will be reflected in the website within 5 minutes. (same as all config changes)

**Comment by martinbndr** [comment]
Could you move or add the abillity to check role/user whitelist on the ``?oauth`` command of modmail.
It is patreon only but the bot still saves the whitelist in the db so this could be used instead of the modmail perm levels. Or make us choose what whiltelists we would like to use maybe?

**Comment by khakers** [comment]
> Could you move or add the abillity to check role/user whitelist on the `?oauth` command of modmail. It is patreon only but the bot still saves the whitelist in the db so this could be used instead of the modmail perm levels. Or make us choose what whiltelists we would like to use maybe?

Hey @martinbndr, this is out of scope for this issue (and it's now closed), could you make a new issue for this?
