### ISSUE TITLE
Mention in Readme that authentication is based on Modmail roles

### ISSUE THREAD

**Issue by svemat01** [khakers/modmail-viewer#36]
Unlike the official log viewer, this one authenticates you based on Modmail roles instead of the whitelist command in the original.

I suggest adding some sort of mention in the setup instructions that a user should be added under a Modmail role.
Another alternative or addition would be to support the traditional oauth2 whitelist as well to some extent.

**Comment by khakers** [comment]
I've written some more information about this on the [permissions wiki page](https://github.com/khakers/modmail-viewer/wiki/Permissions) as part of improving the documentation. Going to close this issue as complete, but let me know if there's anything I should add to it.
