### ISSUE TITLE
[help]:  i try to deploy it on railway but railway is not accepting my github verify how can i fix this so i don't need to pay?

### ISSUE THREAD

**Issue by 13LuckyBack** [khakers/modmail-viewer#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

New

### In which part of the application does the error occur?

Frontend

### Environment

```Markdown
- OS:
- Java:
```

**Comment by khakers** [comment]
Unfortunately I can't do anything about railway verification. If you do have a payment method you can use to verify, you can switch to the dev plan and won't actually be charged anything unless you run enough over their $5 credit which *shouldn't* happen with only small things like modmail-viewer running.

**Comment by khakers** [comment]
You may also be able to find other free services that won't require payment verification, but I don't have anything I can personally recommend and they're generally of poor quality, since free services are highly abused.
